language: scala

scala:
  - 2.11.12

script:
  - sbt clean coverage test coverageReport
  - rm -rf ./target/scala-2.11/coverage-report
  - rm -rf ./target/scala-2.11/scoverage-data
  - rm -rf ./target/scala-2.11/resolution-cache

after_success:
  - bash <(curl -s https://codecov.io/bash)