sudo: required
services:
  - docker
script:
  - sudo docker build . -t scalatest -f ./docker/Dockerfile --build-arg VERSION=$(<./VERSION)
  - sudo docker create -ti --name dummy scalatest bash
  - sudo docker cp dummy:/home/developer/target/scala-2.11/coverage-report/cobertura.xml ./
  - sudo docker rm -fv dummy
  - bash <(curl -s https://codecov.io/bash) -f cobertura.xml